[build]
  publish = "dist"
  command = "npm run build"

[build.processing.html]
  pretty_urls = false

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Netlify Form handling
[build.processing]
  skip_processing = false

[build.processing.forms]
  # Enable Netlify Forms processing
  enabled = true
